sudo: false

language: node_js

matrix:
    fast_finish: true

node_js:
    - '7'
    - '6'
    - '5'
    - '4'
cache:
    directories:
        - node_modules

before_install:
    - npm prune
    - npm update
